// Full indicator catalog for the searchable/favoritable picker. Every entry
// requested is listed — `implemented: true` means the math exists in
// indicators.js and this entry is real and selectable; `implemented: false`
// means it's browsable/favoritable now but selecting it shows "coming soon"
// rather than silently doing nothing or faking a result.
//
// `fn` is the exported indicators.js function name for implemented entries
// (the AppShell integration wires INDICATOR_DEFS off this) — see
// INTEGRATION.md alongside this file for how to wire a new entry in.

export const INDICATOR_CATALOG = [
  { id: "ao", label: "Accelerator Oscillator", category: "Oscillators", type: "pane", implemented: true, fn: "acceleratorOscillator" },
  { id: "adl", label: "Accumulation/Distribution (ADL)", category: "Volume", implemented: false },
  { id: "asi", label: "Accumulative Swing Index", category: "Trend", implemented: false },
  { id: "advdecl", label: "Advance/Decline", category: "Market breadth", implemented: false, note: "Multi-symbol breadth indicator — doesn't apply to a single chart the way the others here do" },
  { id: "alma", label: "Arnaud Legoux Moving Average", category: "Moving Averages", implemented: false },
  { id: "aroon", label: "Aroon", category: "Trend", type: "pane", implemented: true, fn: "aroon" },
  { id: "adx", label: "Average Directional Index (ADX)", category: "Trend", type: "pane", implemented: true, fn: "adx" },
  { id: "avgprice", label: "Average Price", category: "Price", type: "overlay", implemented: true, fn: "averagePrice" },
  { id: "atr", label: "Average True Range (ATR)", category: "Volatility", type: "pane", implemented: true, fn: "atr" },
  { id: "aosc", label: "Awesome Oscillator (AO)", category: "Oscillators", type: "pane", implemented: true, fn: "awesomeOscillator" },
  { id: "bop", label: "Balance of Power (BOP)", category: "Oscillators", type: "pane", implemented: true, fn: "balanceOfPower" },
  { id: "bb", label: "Bollinger Bands (BB)", category: "Volatility", type: "overlay", implemented: true, fn: "bollinger" },
  { id: "bbpb", label: "Bollinger Bands %B", category: "Volatility", implemented: false },
  { id: "bbw", label: "Bollinger Bands Width", category: "Volatility", implemented: false },
  { id: "cmf", label: "Chaikin Money Flow", category: "Volume", type: "pane", implemented: true, fn: "chaikinMoneyFlow" },
  { id: "chosc", label: "Chaikin Oscillator", category: "Volume", implemented: false },
  { id: "chvol", label: "Chaikin Volatility", category: "Volatility", implemented: false },
  { id: "cks", label: "Chande Kroll Stop", category: "Trend", implemented: false },
  { id: "cmo", label: "Chande Momentum Oscillator", category: "Oscillators", implemented: false },
  { id: "chopzone", label: "Chop Zone", category: "Trend", implemented: false },
  { id: "chopidx", label: "Choppiness Index", category: "Trend", implemented: false },
  { id: "cci", label: "Commodity Channel Index (CCI)", category: "Oscillators", type: "pane", implemented: true, fn: "cci" },
  { id: "crsi", label: "Connors RSI", category: "Oscillators", implemented: false },
  { id: "coppock", label: "Coppock Curve", category: "Momentum", implemented: false },
  { id: "corrcoef", label: "Correlation Coefficient", category: "Statistics", implemented: false },
  { id: "corrlog", label: "Correlation - Log", category: "Statistics", implemented: false },
  { id: "dpo", label: "Detrended Price Oscillator", category: "Oscillators", implemented: false },
  { id: "dm", label: "Directional Movement", category: "Trend", type: "pane", implemented: true, fn: "adx", note: "+DI/-DI lines from the same calculation as ADX" },
  { id: "donchian", label: "Donchian Channels", category: "Volatility", type: "overlay", implemented: true, fn: "donchianChannels" },
  { id: "dema", label: "Double EMA", category: "Moving Averages", implemented: false },
  { id: "eom", label: "Ease of Movement", category: "Volume", implemented: false },
  { id: "efi", label: "Elder's Force Index", category: "Volume", type: "pane", implemented: true, fn: "elderForceIndex" },
  { id: "emacross", label: "EMA Cross", category: "Moving Averages", implemented: false },
  { id: "envelopes", label: "Envelopes", category: "Moving Averages", type: "overlay", implemented: true, fn: "envelopes" },
  { id: "fisher", label: "Fisher Transform", category: "Oscillators", implemented: false },
  { id: "gmma", label: "Guppy Multiple Moving Average", category: "Moving Averages", implemented: false },
  { id: "hv", label: "Historical Volatility", category: "Volatility", implemented: false },
  { id: "hma", label: "Hull Moving Average", category: "Moving Averages", implemented: false },
  { id: "ichimoku", label: "Ichimoku Cloud", category: "Trend", type: "overlay", implemented: true, fn: "ichimoku" },
  { id: "keltner", label: "Keltner Channels", category: "Volatility", type: "overlay", implemented: true, fn: "keltnerChannels" },
  { id: "klinger", label: "Klinger Oscillator", category: "Volume", implemented: false },
  { id: "kst", label: "Know Sure Thing (KST)", category: "Momentum", implemented: false },
  { id: "lsma", label: "Least Squares Moving Average", category: "Moving Averages", implemented: false },
  { id: "lrc", label: "Linear Regression Curve", category: "Trend", implemented: false },
  { id: "lrs", label: "Linear Regression Slope", category: "Trend", implemented: false },
  { id: "macross", label: "MA Cross", category: "Moving Averages", implemented: false },
  { id: "maemacross", label: "MA with EMA Cross", category: "Moving Averages", implemented: false },
  { id: "massindex", label: "Mass Index", category: "Volatility", implemented: false },
  { id: "mcginley", label: "McGinley Dynamic", category: "Moving Averages", implemented: false },
  { id: "medianprice", label: "Median Price", category: "Price", type: "overlay", implemented: true, fn: "medianPrice" },
  { id: "momentum", label: "Momentum", category: "Momentum", type: "pane", implemented: true, fn: "momentum" },
  { id: "mfi", label: "Money Flow Index (MFI)", category: "Volume", type: "pane", implemented: true, fn: "moneyFlowIndex" },
  { id: "ma", label: "Moving Average", category: "Moving Averages", type: "overlay", implemented: true, fn: "sma" },
  { id: "machannel", label: "Moving Average Channel", category: "Moving Averages", implemented: false },
  { id: "macd", label: "Moving Average Convergence/Divergence (MACD)", category: "Momentum", type: "pane", implemented: true, fn: "macd" },
  { id: "netvol", label: "Net Volume", category: "Volume", implemented: false },
  { id: "obv", label: "On Balance Volume (OBV)", category: "Volume", type: "pane", implemented: true, fn: "obv" },
  { id: "psar", label: "Parabolic SAR", category: "Trend", implemented: false },
  { id: "pivots", label: "Pivot Points Standard", category: "Trend", implemented: false },
  { id: "pricechannel", label: "Price Channel", category: "Volatility", implemented: false },
  { id: "priceosc", label: "Price Oscillator", category: "Momentum", implemented: false },
  { id: "pvt", label: "Price Volume Trend", category: "Volume", implemented: false },
  { id: "rankcorr", label: "Rank Correlation Index", category: "Statistics", implemented: false },
  { id: "roc", label: "Rate Of Change (ROC)", category: "Momentum", type: "pane", implemented: true, fn: "roc" },
  { id: "ratio", label: "Ratio", category: "Statistics", implemented: false },
  { id: "rsi", label: "Relative Strength Index (RSI)", category: "Oscillators", type: "pane", implemented: true, fn: "rsi" },
  { id: "rvi", label: "Relative Vigor Index", category: "Oscillators", implemented: false },
  { id: "rvolidx", label: "Relative Volatility Index", category: "Volatility", implemented: false },
  { id: "stderr", label: "Standard Error", category: "Statistics", implemented: false },
  { id: "stderrbands", label: "Standard Error Bands", category: "Statistics", implemented: false },
  { id: "smiergodic", label: "SMI Ergodic Indicator/Oscillator", category: "Oscillators", implemented: false },
  { id: "smma", label: "Smoothed Moving Average", category: "Moving Averages", implemented: false },
  { id: "stddev", label: "Standard Deviation", category: "Statistics", type: "pane", implemented: true, fn: "standardDeviation" },
  { id: "stoch", label: "Stochastic", category: "Oscillators", type: "pane", implemented: true, fn: "stochastic" },
  { id: "stochrsi", label: "Stochastic RSI", category: "Oscillators", type: "pane", implemented: true, fn: "stochRsi" },
  { id: "supertrend", label: "SuperTrend", category: "Trend", type: "overlay", implemented: true, fn: "superTrend" },
  { id: "spread", label: "Spread", category: "Price", implemented: false },
  { id: "trix", label: "TRIX", category: "Momentum", type: "pane", implemented: true, fn: "trix" },
  { id: "tema", label: "Triple EMA", category: "Moving Averages", implemented: false },
  { id: "tsi", label: "True Strength Indicator", category: "Momentum", implemented: false },
  { id: "trendstrength", label: "Trend Strength Index", category: "Trend", implemented: false },
  { id: "typicalprice", label: "Typical Price", category: "Price", type: "overlay", implemented: true, fn: "typicalPrice" },
  { id: "ultosc", label: "Ultimate Oscillator", category: "Oscillators", type: "pane", implemented: true, fn: "ultimateOscillator" },
  { id: "volc2c", label: "Volatility Close-to-Close", category: "Volatility", implemented: false },
  { id: "volzeroc2c", label: "Volatility Zero Trend Close-to-Close", category: "Volatility", implemented: false },
  { id: "volohlc", label: "Volatility O-H-L-C", category: "Volatility", implemented: false },
  { id: "volidx", label: "Volatility Index", category: "Volatility", implemented: false },
  { id: "vwap", label: "VWAP", category: "Volume", type: "overlay", implemented: true, fn: "vwap" },
  { id: "vwma", label: "VWMA", category: "Volume", type: "overlay", implemented: true, fn: "vwma" },
  { id: "volosc", label: "Volume Oscillator", category: "Volume", implemented: false },
  { id: "volprofile", label: "Volume Profile", category: "Volume", implemented: false, note: "Needs a horizontal histogram rendered on the price axis — a different rendering approach from every other indicator here" },
  { id: "vortex", label: "Vortex Indicator", category: "Trend", implemented: false },
  { id: "volume", label: "Volume", category: "Volume", type: "overlay", implemented: true, fn: null, note: "Already rendered on the main chart by default" },
  { id: "williamsr", label: "Williams %R", category: "Oscillators", type: "pane", implemented: true, fn: "williamsR" },
  { id: "alligator", label: "Williams Alligator", category: "Trend", implemented: false },
  { id: "fractal", label: "Williams Fractal", category: "Trend", implemented: false },
  { id: "zigzag", label: "Zig Zag", category: "Trend", implemented: false },
];
