// Full indicator catalog for the searchable/favoritable picker. Every entry
// requested is listed — `implemented: true` means the math is real and this
// entry is selectable; `implemented: false` means it's browsable/favoritable
// now but selecting it shows "coming soon" rather than faking a result.
//
// `fn` is the exported function name (from indicators.js or
// indicatorsBatch3.js — see `module` field) for implemented entries.
//
// Structurally deferred (not a laziness gap — genuinely can't work yet):
// Volume Profile needs a histogram-on-price-axis rendering, entirely
// different from every line/pane indicator here. Advance/Decline needs
// multi-symbol market-breadth data this single-chart app doesn't have.
// Ratio, Spread, Correlation Coefficient, Correlation-Log, and Rank
// Correlation Index all inherently compare two symbols — there's no
// second-symbol picker in the UI. Trend Strength Index has no single
// confidently-known canonical formula distinct from ADX under that name.
// Accumulative Swing Index needs a "limit move" constant that's
// asset-specific and undefined for crypto — left out rather than guess.

export const INDICATOR_CATALOG = [
  { id: "ao", label: "Accelerator Oscillator", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "acceleratorOscillator" },
  { id: "adl", label: "Accumulation/Distribution (ADL)", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "adl" },
  { id: "asi", label: "Accumulative Swing Index", category: "Trend", implemented: false, note: "Needs an asset-specific \"limit move\" constant that's undefined for crypto" },
  { id: "advdecl", label: "Advance/Decline", category: "Market breadth", implemented: false, note: "Multi-symbol breadth indicator — doesn't apply to a single chart the way the others here do" },
  { id: "alma", label: "Arnaud Legoux Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "alma" },
  { id: "aroon", label: "Aroon", category: "Trend", type: "pane", implemented: true, module: "indicators", fn: "aroon" },
  { id: "adx", label: "Average Directional Index (ADX)", category: "Trend", type: "pane", implemented: true, module: "indicators", fn: "adx" },
  { id: "avgprice", label: "Average Price", category: "Price", type: "overlay", implemented: true, module: "indicators", fn: "averagePrice" },
  { id: "atr", label: "Average True Range (ATR)", category: "Volatility", type: "pane", implemented: true, module: "indicators", fn: "atr" },
  { id: "aosc", label: "Awesome Oscillator (AO)", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "awesomeOscillator" },
  { id: "bop", label: "Balance of Power (BOP)", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "balanceOfPower" },
  { id: "bb", label: "Bollinger Bands (BB)", category: "Volatility", type: "overlay", implemented: true, module: "indicators", fn: "bollinger" },
  { id: "bbpb", label: "Bollinger Bands %B", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "bbPercentB" },
  { id: "bbw", label: "Bollinger Bands Width", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "bbWidth" },
  { id: "cmf", label: "Chaikin Money Flow", category: "Volume", type: "pane", implemented: true, module: "indicators", fn: "chaikinMoneyFlow" },
  { id: "chosc", label: "Chaikin Oscillator", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "chaikinOscillator" },
  { id: "chvol", label: "Chaikin Volatility", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "chaikinVolatility" },
  { id: "cks", label: "Chande Kroll Stop", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "chandeKrollStop" },
  { id: "cmo", label: "Chande Momentum Oscillator", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "chandeMomentumOscillator" },
  { id: "chopzone", label: "Chop Zone", category: "Trend", type: "pane", implemented: true, module: "batch3", fn: "chopZone" },
  { id: "chopidx", label: "Choppiness Index", category: "Trend", type: "pane", implemented: true, module: "batch3", fn: "choppinessIndex" },
  { id: "cci", label: "Commodity Channel Index (CCI)", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "cci" },
  { id: "crsi", label: "Connors RSI", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "connorsRsi" },
  { id: "coppock", label: "Coppock Curve", category: "Momentum", type: "pane", implemented: true, module: "batch3", fn: "coppockCurve" },
  { id: "corrcoef", label: "Correlation Coefficient", category: "Statistics", implemented: false, note: "Compares two symbols — no second-symbol picker in the UI yet" },
  { id: "corrlog", label: "Correlation - Log", category: "Statistics", implemented: false, note: "Compares two symbols — no second-symbol picker in the UI yet" },
  { id: "dpo", label: "Detrended Price Oscillator", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "detrendedPriceOscillator" },
  { id: "dm", label: "Directional Movement", category: "Trend", type: "pane", implemented: true, module: "indicators", fn: "adx", note: "+DI/-DI lines from the same calculation as ADX" },
  { id: "donchian", label: "Donchian Channels", category: "Volatility", type: "overlay", implemented: true, module: "indicators", fn: "donchianChannels" },
  { id: "dema", label: "Double EMA", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "dema" },
  { id: "eom", label: "Ease of Movement", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "easeOfMovement" },
  { id: "efi", label: "Elder's Force Index", category: "Volume", type: "pane", implemented: true, module: "indicators", fn: "elderForceIndex" },
  { id: "emacross", label: "EMA Cross", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "emaCross" },
  { id: "envelopes", label: "Envelopes", category: "Moving Averages", type: "overlay", implemented: true, module: "indicators", fn: "envelopes" },
  { id: "fisher", label: "Fisher Transform", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "fisherTransform" },
  { id: "gmma", label: "Guppy Multiple Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "guppyMma" },
  { id: "hv", label: "Historical Volatility", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "historicalVolatility" },
  { id: "hma", label: "Hull Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "hma" },
  { id: "ichimoku", label: "Ichimoku Cloud", category: "Trend", type: "overlay", implemented: true, module: "indicators", fn: "ichimoku" },
  { id: "keltner", label: "Keltner Channels", category: "Volatility", type: "overlay", implemented: true, module: "indicators", fn: "keltnerChannels" },
  { id: "klinger", label: "Klinger Oscillator", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "klingerOscillator" },
  { id: "kst", label: "Know Sure Thing (KST)", category: "Momentum", type: "pane", implemented: true, module: "batch3", fn: "kst" },
  { id: "lsma", label: "Least Squares Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "lsma" },
  { id: "lrc", label: "Linear Regression Curve", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "linearRegressionCurve" },
  { id: "lrs", label: "Linear Regression Slope", category: "Trend", type: "pane", implemented: true, module: "batch3", fn: "linearRegressionSlope" },
  { id: "macross", label: "MA Cross", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "maCross" },
  { id: "maemacross", label: "MA with EMA Cross", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "maWithEmaCross" },
  { id: "massindex", label: "Mass Index", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "massIndex" },
  { id: "mcginley", label: "McGinley Dynamic", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "mcginleyDynamic" },
  { id: "medianprice", label: "Median Price", category: "Price", type: "overlay", implemented: true, module: "indicators", fn: "medianPrice" },
  { id: "momentum", label: "Momentum", category: "Momentum", type: "pane", implemented: true, module: "indicators", fn: "momentum" },
  { id: "mfi", label: "Money Flow Index (MFI)", category: "Volume", type: "pane", implemented: true, module: "indicators", fn: "moneyFlowIndex" },
  { id: "ma", label: "Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "indicators", fn: "sma" },
  { id: "machannel", label: "Moving Average Channel", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "movingAverageChannel" },
  { id: "macd", label: "Moving Average Convergence/Divergence (MACD)", category: "Momentum", type: "pane", implemented: true, module: "indicators", fn: "macd" },
  { id: "netvol", label: "Net Volume", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "netVolume" },
  { id: "obv", label: "On Balance Volume (OBV)", category: "Volume", type: "pane", implemented: true, module: "indicators", fn: "obv" },
  { id: "psar", label: "Parabolic SAR", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "parabolicSar" },
  { id: "pivots", label: "Pivot Points Standard", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "pivotPointsStandard", note: "Rolls bar-to-bar rather than using fixed session boundaries (this chart doesn't track session boundaries)" },
  { id: "pricechannel", label: "Price Channel", category: "Volatility", type: "overlay", implemented: true, module: "indicators", fn: "donchianChannels", note: "Same calculation as Donchian Channels" },
  { id: "priceosc", label: "Price Oscillator", category: "Momentum", type: "pane", implemented: true, module: "batch3", fn: "priceOscillator" },
  { id: "pvt", label: "Price Volume Trend", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "priceVolumeTrend" },
  { id: "rankcorr", label: "Rank Correlation Index", category: "Statistics", implemented: false, note: "Compares two symbols — no second-symbol picker in the UI yet" },
  { id: "roc", label: "Rate Of Change (ROC)", category: "Momentum", type: "pane", implemented: true, module: "indicators", fn: "roc" },
  { id: "ratio", label: "Ratio", category: "Statistics", implemented: false, note: "Compares two symbols — no second-symbol picker in the UI yet" },
  { id: "rsi", label: "Relative Strength Index (RSI)", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "rsi" },
  { id: "rvi", label: "Relative Vigor Index", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "relativeVigorIndex" },
  { id: "rvolidx", label: "Relative Volatility Index", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "relativeVolatilityIndex" },
  { id: "stderr", label: "Standard Error", category: "Statistics", type: "pane", implemented: true, module: "batch3", fn: "standardError" },
  { id: "stderrbands", label: "Standard Error Bands", category: "Statistics", type: "overlay", implemented: true, module: "batch3", fn: "standardErrorBands" },
  { id: "smiergodic", label: "SMI Ergodic Indicator/Oscillator", category: "Oscillators", type: "pane", implemented: true, module: "batch3", fn: "smiErgodic" },
  { id: "smma", label: "Smoothed Moving Average", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "smma" },
  { id: "stddev", label: "Standard Deviation", category: "Statistics", type: "pane", implemented: true, module: "indicators", fn: "standardDeviation" },
  { id: "stoch", label: "Stochastic", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "stochastic" },
  { id: "stochrsi", label: "Stochastic RSI", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "stochRsi" },
  { id: "supertrend", label: "SuperTrend", category: "Trend", type: "overlay", implemented: true, module: "indicators", fn: "superTrend" },
  { id: "spread", label: "Spread", category: "Price", implemented: false, note: "Compares two symbols — no second-symbol picker in the UI yet" },
  { id: "trix", label: "TRIX", category: "Momentum", type: "pane", implemented: true, module: "indicators", fn: "trix" },
  { id: "tema", label: "Triple EMA", category: "Moving Averages", type: "overlay", implemented: true, module: "batch3", fn: "tema" },
  { id: "tsi", label: "True Strength Indicator", category: "Momentum", type: "pane", implemented: true, module: "batch3", fn: "trueStrengthIndex" },
  { id: "trendstrength", label: "Trend Strength Index", category: "Trend", implemented: false, note: "No single confidently-known canonical formula under this exact name, distinct from ADX" },
  { id: "typicalprice", label: "Typical Price", category: "Price", type: "overlay", implemented: true, module: "indicators", fn: "typicalPrice" },
  { id: "ultosc", label: "Ultimate Oscillator", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "ultimateOscillator" },
  { id: "volc2c", label: "Volatility Close-to-Close", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "volatilityCloseToClose" },
  { id: "volzeroc2c", label: "Volatility Zero Trend Close-to-Close", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "volatilityZeroTrendCloseToClose" },
  { id: "volohlc", label: "Volatility O-H-L-C", category: "Volatility", type: "pane", implemented: true, module: "batch3", fn: "volatilityOHLC" },
  { id: "volidx", label: "Volatility Index", category: "Volatility", implemented: false, note: "No single confidently-known canonical definition distinct from the other volatility variants here" },
  { id: "vwap", label: "VWAP", category: "Volume", type: "overlay", implemented: true, module: "indicators", fn: "vwap" },
  { id: "vwma", label: "VWMA", category: "Volume", type: "overlay", implemented: true, module: "indicators", fn: "vwma" },
  { id: "volosc", label: "Volume Oscillator", category: "Volume", type: "pane", implemented: true, module: "batch3", fn: "volumeOscillator" },
  { id: "volprofile", label: "Volume Profile", category: "Volume", implemented: false, note: "Needs a horizontal histogram rendered on the price axis — a different rendering approach from every other indicator here" },
  { id: "vortex", label: "Vortex Indicator", category: "Trend", type: "pane", implemented: true, module: "batch3", fn: "vortexIndicator" },
  { id: "volume", label: "Volume", category: "Volume", type: "overlay", implemented: true, module: null, fn: null, note: "Already rendered on the main chart by default" },
  { id: "williamsr", label: "Williams %R", category: "Oscillators", type: "pane", implemented: true, module: "indicators", fn: "williamsR" },
  { id: "alligator", label: "Williams Alligator", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "williamsAlligator" },
  { id: "fractal", label: "Williams Fractal", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "williamsFractal" },
  { id: "zigzag", label: "Zig Zag", category: "Trend", type: "overlay", implemented: true, module: "batch3", fn: "zigZag" },
];
